spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/goldscale?replicaSet=rs0
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  auth:
    username: admin
    password: admin
